### ISSUE TITLE
Is it safe to use neovim-ui in place of popup.nvim and plenary.nvim?

### ISSUE THREAD

**Issue by bjdm** [mjlbach/neovim-ui#10]
The source for neovim-ui/popup and popup.nvim/plenary.nvim appears to be mostly the same aside from use of vim.fn.* in popup.nvim and vim.api.* in neovim-ui.

If this is correct, is it safe to use neovim-ui for popups in a plugin?

**Comment by mjlbach** [comment]
I would not currently recommend using neovim-ui, it's more so smolck and I can collaborate on it for now.

I don't foresee spending much time on this until after 0.5 releases, so I imagine the timeline for a feature-complete/stable neovim-ui is on the order of 2-4 months.

**Comment by bjdm** [comment]
Many thanks! Look forward to testing the project post v0.5
