### ISSUE TITLE
Pickers (pick one, many, async/sync)

### ISSUE THREAD

**Issue by mfussenegger** [mjlbach/neovim-ui#12]
In both nvim-dap and nvim-jdtls I've build some picker methods:

```
function M.pick_one_async(items, prompt, label_fn, cb)
function M.pick_one(items, prompt, label_fn)
function M.pick_many(items, prompt, label_f)
```

The `items` here is an arbitrary list of arbitrary items and `label_fn` is used to render out an item. So it receives an item and must return a string.
In theory `items` could also be a function that follows the iterator protocol, to support lazy data generation use-cases as well.
The implementation must then take care to call the callback or return the selected item. (The whole object from the options, not an index or so)

They've a `inputlist` based default implementation and there are some recipes how to replace them with fancier implementations. For example to use telescope instead.
I think it would be cool if `vim.ui` would contain these so that this pattern becomes more established and we have a more consistent UI experience across plugins.

I'm pretty happy with the API so far as it is both flexible enough and also simple to use. I've seen other picker APIs (e.g. in vscode), where are always extra mapping steps necessary - you need to map your structures to a `{label:, value:}` and then based on that figure out which of *your* items the user really selected.

**Comment by ckipp01** [comment]
I'm all for providing a way to reduce boilerplate and de-duplicating efforts around this area. Following up on out [twitter convo](https://twitter.com/mfussenegger/status/1401828087759785987?s=20), I'm a bit curious how this would all fit together. For the sake of an example, let's say I want to use the `function M.pick_one_async(items, prompt, label_fn, cb)` equivalent for a user to choose a command to execute in [nvim-metals](https://github.com/scalameta/nvim-metals).

There can be a very generic way to do this with like an input list or something, but let's say like in my case I decide I want to use Telescope for this. I think I get how Telescope could map the actual `items`, `prompt`, `label_fn`, and the `cb`, but what about the very extension specific parts? Just to name a few: how wide something is, if there is a preview, what type of preview should be used for this specific picker etc. I'm sure some other pickers may have some picker-specific details as well. It's not clear to me how generalizing this can also allow for that level of customisability. Any thoughts?

**Comment by mfussenegger** [comment]
>  I think I get how Telescope could map the actual items, prompt, label_fn, and the cb, but what about the very extension specific parts? Just to name a few: how wide something is, if there is a preview, what type of preview should be used for this specific picker etc. I'm sure some other pickers may have some picker-specific details as well. It's not clear to me how generalizing this can also allow for that level of customisability. Any thoughts?


I think there are two separate issues here:

- One is how much functionality the common API should expose. The main challenge here will probably be to agree on something. But my take would be to start out with limited functionality and expose as we go and as new use-cases pop up. TJ would probably have lots of good inputs here based on the experience with telescope.

- Separating the concerns. Plugins that use the APIs should limit themselves to dictating as little as possible. E.g. you focus on "here are some options, make a choice". How these choices are presented should be up to the implementation and the implementation specific configuration. nvim-metals wouldn't choose if it uses a popup and how wide it would be or what fuzzy matcher algorithm. But a "picker provider implementation" could make it configurable and allow the user to set it when they register the provider. (Maybe https://github.com/mfussenegger/nvim-jdtls/wiki/UI-Extensions gives an idea how this could work). The advantage is that users get a consistent experience across all plugins who follow this model. The downside is that as plugin author you have less influence over of how things are styled. (To me that's also a good thing :p)

**Comment by clason** [comment]
>  The advantage is that users get a consistent experience across all plugins who follow this model. The downside is that as plugin author you have less influence over of how things are styled. (To me that's also a good thing :p)

And a GUI can go ham with it and make nyancat fly over the selected option.

(Less facetiously, can use a consistent GUI chrome for all neovim and plugin UX.)

**Comment by teto** [comment]
I would envision a `function M.pick(items, opts)` with `opts = { prompt=..., fuzzy =..., multiselect = ... }`and items a dict key: value (we can start with without the fuzzy/multiselect). 
I would even see the interface directly in core (like for vim.notify) since it's straightforward to do with lots of leverage (many plugins need a picker). It would default to inputlist as you did and then one can plug its fzf/telescope picker behind. 
`vim.ui.pick = my_function`

**Comment by mfussenegger** [comment]
> I would envision a function M.pick(items, opts) with opts = { prompt=..., fuzzy =..., multiselect = ... }and items a dict key: value (we can start with without the fuzzy/multiselect).

What would be the possible arguments to the `fuzzy` options?
I question whether a plugin author who uses the `M.pick` function should be able to dictate whether fuzzy matching should be used - and if so which algorithm. I think that should be up for the plugins provide alternative implementations and for the users to configure.  Something like a `telescope.register_as_picker { fuzzy = ... }`

**Comment by teto** [comment]
y I shouldn't have put the fuzzy setting, it's confusing (let's forget about it). What I wanted to say is that we can have a minimal implementation first so that plugins build on it, and before release, refine the `options` as we did for 0.5.

**Comment by mfussenegger** [comment]
I think with `vim.ui.select` in core we can close this.
